project_id = "jquhgyqoepmysvoxxgji"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://jquhgyqoepmysvoxxgji.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = true

[db]
port = 54322

[functions.process-orders]
verify_jwt = false

[functions.auto-process-orders]
verify_jwt = false

[functions.debug-orders]
verify_jwt = false

[functions.manager-motoboy-orders]
verify_jwt = false

[functions.manager-handle-motoboy-order]
verify_jwt = false

[functions.motoboy-list-orders]
verify_jwt = false

[functions.motoboy-handle-order]
verify_jwt = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324